on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Validate a release

jobs:
  sanity_check_release:
    name: Sanity check the release
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Install JQ
        run: sudo apt-get update && sudo apt install -y jq
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate the release
        run: ./release-scripts/validate-release.sh
  verify_osx_release:
    name: Verify the OSX brew package
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install JQ
        run: brew install jq
      - name: Validate the release
        run: ./release-scripts/validate-osx-release.sh

